// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBl8d6Abjh4fwfUcjPtOxohAOdxcdlETg8',
    appId: '1:141457328070:web:171473e1f643b365bcd4c7',
    messagingSenderId: '141457328070',
    projectId: 'ninja-brew-crew-634b4',
    authDomain: 'ninja-brew-crew-634b4.firebaseapp.com',
    storageBucket: 'ninja-brew-crew-634b4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCz99RUxX2phMJxXGsMS_yXaMwP5Nyosok',
    appId: '1:141457328070:android:b9ba2fa40b8f9c99bcd4c7',
    messagingSenderId: '141457328070',
    projectId: 'ninja-brew-crew-634b4',
    storageBucket: 'ninja-brew-crew-634b4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeiClAYjrvIHdHVmTrpcTDx9x7i2M9RZQ',
    appId: '1:141457328070:ios:e9dfd742575f746bbcd4c7',
    messagingSenderId: '141457328070',
    projectId: 'ninja-brew-crew-634b4',
    storageBucket: 'ninja-brew-crew-634b4.appspot.com',
    iosBundleId: 'com.example.firebaseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeiClAYjrvIHdHVmTrpcTDx9x7i2M9RZQ',
    appId: '1:141457328070:ios:a4420d7f1d046817bcd4c7',
    messagingSenderId: '141457328070',
    projectId: 'ninja-brew-crew-634b4',
    storageBucket: 'ninja-brew-crew-634b4.appspot.com',
    iosBundleId: 'com.example.firebaseApp.RunnerTests',
  );
}
